from collections.abc import Sequence
from typing import Any

class YoutubeDL:
    def __init__(self, params: dict[str, Any] | None = ...) -> None: ...
    def __enter__(self) -> YoutubeDL: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: object | None,
    ) -> None: ...
    def extract_info(self, url: str, download: bool = ...) -> dict[str, Any] | Any: ...
    def download(self, url_list: Sequence[str]) -> int: ...
